# Generated by Django 4.2.2 on 2023-07-03 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_category_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
