# Generated by Django 4.2.2 on 2023-07-03 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_category_categoryid'),
    ]

    operations = [
    migrations.AlterField(
        model_name='category',
        name='CategoryID',
        field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
    ),
    ]
