# Generated by Django 4.2.2 on 2023-07-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_category_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
