# Generated by Django 4.2.2 on 2023-07-05 21:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
