# Generated by Django 4.2.2 on 2023-07-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
