# Generated by Django 4.2.2 on 2023-07-20 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersdetails',
            name='OrderDetailID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
