# Generated by Django 4.2.2 on 2023-07-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_ordersdetails_orderdetailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='OrderID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordersdetails',
            name='OrderDetailID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
